veg1=input("What is your first favourite vegetable?\n>")
veg2=input("What is your second favourite vegetable?\n>")
veg3=input("What is your third favourite vegetable?\n>")
print()
print(veg1, veg2, veg3, sep=", ")
print()
print()
print(veg3)
print(veg2)
print(veg1)
print(\n)
print()
print(veg3 + "!")
print(veg2 + "!")
print(veg1 + "!")
